# Generated by Django 4.1.6 on 2023-02-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('Срочно и Важно', 'Срочно и Важно'), ('Срочно', 'Срочно'), ('Важно', 'Важно'), ('Не особо важно', 'Не особо важно')], default='Важно', max_length=128, verbose_name='важность'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='actualEndDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='реально закончено'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='actualStartDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='реально начато'),
        ),
    ]
