# Generated by Django 4.1.6 on 2023-02-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_importance_alter_todo_actualenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todoapp.todo', verbose_name='задача'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('Срочно и Важно', 'Срочно и Важно'), ('Срочно', 'Срочно'), ('Важно', 'Важно'), ('Cредне', 'Cредне'), ('Не особо важно', 'Не особо важно')], default='Cредне', max_length=128, verbose_name='важность'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='todoapp.todolist', verbose_name='список дел'),
        ),
    ]
